[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "skia-canvas-pyr"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]
description = "A Python canvas library powered by Skia, with bindings implemented in Rust."
readme = "README.md"
keywords = ["rust", "skia", "canvas"]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/yetsing/skia-canvas-pyr"
Repository = "https://github.com/yetsing/skia-canvas-pyr"
Changelog = "https://github.com/yetsing/skia-canvas-pyr/blob/master/CHANGELOG.md"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "tomli>=2.4.0",
]

[tool.maturin]
profile = "dev"
editable-profile = "dev"
features = ["vulkan", "window", "freetype"]
include = ["fonts"]

[tool.uv]
# uv 不要构建本项目
package = false

[tool.skia_canvas_pyr.upstream]
name = "skia-canvas"
version = "3.0.8"
commit = "042312a3f40b660b1d7dc0beba541486171bc5cc"
url = "https://github.com/samizdatco/skia-canvas"
license = "MIT"

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "tomli>=2.4.0",
]
