from __future__ import annotations

from typing import (
    Any,
    Literal,
    Sequence,
    TypeAlias,
    Tuple,
    List,
    TypedDict,
    Protocol,
    Dict,
    Final,
)

PathOpName = Literal[
    "difference",
    "intersect",
    "union",
    "xor",
    "reversedifference",
    "complement",
]
FillRule = Literal["nonzero", "evenodd"]
EdgeCommand = Literal[
    "moveTo",
    "lineTo",
    "quadraticCurveTo",
    "bezierCurveTo",
    "conicCurveTo",
    "closePath",
]

# 实际上第一个是命令字符串，第二个及以后的都是 float 参数
Path2DEdge: TypeAlias = Tuple[EdgeCommand | float, ...]

class Path2D:
    def __init__(self) -> None: ...
    @staticmethod
    def from_path(other_path: Path2D) -> Path2D: ...
    @staticmethod
    def from_svg(d: str) -> Path2D: ...
    def add_path(
        self, other: Path2D, transform: Sequence[float] | None = None
    ) -> None: ...
    def close_path(self) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def line_to(self, x: float, y: float) -> None: ...
    def bezier_curve_to(
        self, cp1x: float, cp1y: float, cp2x: float, cp2y: float, x: float, y: float
    ) -> None: ...
    def quadratic_curve_to(
        self, cpx: float, cpy: float, x: float, y: float
    ) -> None: ...
    def conic_curve_to(
        self, cpx: float, cpy: float, x: float, y: float, weight: float
    ) -> None: ...
    def arc(
        self,
        x: float,
        y: float,
        radius: float,
        start_angle: float,
        end_angle: float,
        counterclockwise: bool | None = None,
    ) -> None: ...
    def arc_to(
        self, x1: float, y1: float, x2: float, y2: float, radius: float
    ) -> None: ...
    def ellipse(
        self,
        x: float,
        y: float,
        radius_x: float,
        radius_y: float,
        rotation: float,
        start_angle: float,
        end_angle: float,
        counterclockwise: bool | None = None,
    ) -> None: ...
    def rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def round_rect(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        top_left_radius_x: float,
        top_left_radius_y: float,
        top_right_radius_x: float,
        top_right_radius_y: float,
        bottom_right_radius_x: float,
        bottom_right_radius_y: float,
        bottom_left_radius_x: float,
        bottom_left_radius_y: float,
    ) -> None: ...
    def op(self, other: Path2D, operation: PathOpName) -> Path2D: ...
    def interpolate(self, other: Path2D, weight: float) -> Path2D: ...
    def simplify(self, fill_rule: FillRule | None = None) -> Path2D: ...
    def unwind(self) -> Path2D: ...
    def offset(self, dx: float, dy: float) -> Path2D: ...
    def transform(self, matrix: Sequence[float]) -> Path2D: ...
    def round(self, radius: float) -> Path2D: ...
    def trim(
        self,
        begin: float,
        end: float,
        inverted: bool | None = None,
    ) -> Path2D: ...
    def jitter(
        self, segment_length: float, variance: float, seed: float | None = None
    ) -> Path2D: ...
    def bounds(self) -> Path2DBounds: ...
    def contains(self, x: float, y: float) -> bool: ...
    def edges(self) -> List[Path2DEdge]: ...
    def get_d(self) -> str: ...
    def set_d(self, p: str) -> None: ...

class Path2DBounds:
    top: float
    left: float
    bottom: float
    right: float
    width: float
    height: float

class CanvasTexture:
    def __init__(
        self,
        line: float,
        cap: str,
        angle: float,
        outline: bool,
        h: float,
        v: float,
        x: float,
        y: float,
        path: None | Path2D,
        color: None | str,
    ) -> None: ...
    def repr(self) -> str: ...

class CanvasGradient:
    @staticmethod
    def linear(x1: float, y1: float, x2: float, y2: float) -> CanvasGradient: ...
    @staticmethod
    def radial(
        x1: float,
        y1: float,
        r1: float,
        x2: float,
        y2: float,
        r2: float,
    ) -> CanvasGradient: ...
    @staticmethod
    def conic(theta: float, x: float, y: float) -> CanvasGradient: ...
    def add_color_stop(self, offset: float, color: str) -> None: ...
    def repr(self) -> str: ...

class Image:
    def __init__(self) -> None: ...
    def get_src(self) -> str: ...
    def set_src(self, src: str) -> None: ...
    def set_data(self, buffer: bytes) -> bool: ...
    def get_width(self) -> float: ...
    def get_height(self) -> float: ...
    def get_complete(self) -> bool: ...
    def pixels(
        self,
        color_type: str | None,
        color_space: str | None,
    ) -> List[int] | None: ...

class CanvasPattern:
    @staticmethod
    def from_image(
        src: Image,
        canvas_width: float,
        canvas_height: float,
        repetition: str | None,
    ) -> CanvasPattern: ...
    @staticmethod
    def from_image_data(
        src: "ImageData",
        repetition: str | None,
    ) -> CanvasPattern: ...
    @staticmethod
    def from_canvas(src: "Context2D", repetition: str | None) -> CanvasPattern: ...
    def set_transform(self, matrix: Sequence[float]) -> None: ...
    def repr(self) -> str: ...

class ExportOptions(TypedDict):
    format: str
    quality: float
    density: float
    downsample: bool
    matte: str | None
    msaa: float | None
    color_type: str | None
    text_contrast: float
    text_gamma: float
    outline: bool

class Canvas:
    def __init__(
        self,
        text_contrast: float | None,
        text_gamma: float | None,
        gpu_enabled: bool,
    ) -> None: ...
    def get_width(self) -> float: ...
    def get_height(self) -> float: ...
    def set_width(self, width: float) -> None: ...
    def set_height(self, height: float) -> None: ...
    def get_engine(self) -> str: ...
    def set_engine(self, engine_name: str) -> None: ...
    def get_engine_status(self) -> str: ...
    def to_buffer_sync(
        self, pages: Sequence[Context2D], options: ExportOptions
    ) -> bytes: ...
    def save_sync(
        self,
        pages: Sequence[Context2D],
        name_pattern: str,
        padding: float | None,
        options: ExportOptions,
    ) -> None: ...

class ImageData(Protocol):
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def color_type(self) -> str: ...
    @property
    def color_space(self) -> str: ...
    @property
    def data(self) -> bytes: ...

class ImageDataExportOptions(Protocol):
    color_type: str | None
    color_space: str | None
    matte: str | None
    density: float | None
    msaa: float | None

class Font(Protocol):
    family: List[str]
    canonical: str
    variant: str
    size: float
    weight: float
    style: str
    stretch: str
    lineHeight: float | None
    features: Dict[str, float | List[str]]

class FontVariant(Protocol):
    variant: str
    features: Dict[str, float | List[str]]

class Spacing(Protocol):
    size: float
    unit: str
    px: float

class DecorationStyle(Protocol):
    text: str
    line: str
    style: str
    color: str
    inherit: str
    thickness: Spacing | None

class Filter(Protocol):
    canonical: str
    filters: Dict[str, float | Tuple[float, float, float, str]]

class Context2D:
    def __init__(self, canvas: Canvas) -> None: ...
    def reset_size(self, canvas: Canvas) -> None: ...
    def get_size(self) -> Tuple[float, float]: ...
    def set_size(self, width: float, height: float) -> None: ...
    def reset(self) -> None: ...
    def save(self) -> None: ...
    def restore(self) -> None: ...
    def transform(self, matrix: Sequence[float]) -> None: ...
    def translate(self, x: float, y: float) -> None: ...
    def scale(self, x: float, y: float) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def reset_transform(self) -> None: ...
    def create_projection(
        self, dst: Sequence[float], src: Sequence[float]
    ) -> List[float]: ...
    def get_current_transform(self) -> List[float]: ...
    def set_current_transform(self, matrix: Sequence[float]) -> None: ...
    def begin_path(self) -> None: ...
    def rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def round_rect(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        top_left_radius_x: float,
        top_left_radius_y: float,
        top_right_radius_x: float,
        top_right_radius_y: float,
        bottom_right_radius_x: float,
        bottom_right_radius_y: float,
        bottom_left_radius_x: float,
        bottom_left_radius_y: float,
    ) -> None: ...
    def arc(
        self,
        x: float,
        y: float,
        radius: float,
        start_angle: float,
        end_angle: float,
        counterclockwise: bool,
    ) -> None: ...
    def ellipse(
        self,
        x: float,
        y: float,
        radius_x: float,
        radius_y: float,
        rotation: float,
        start_angle: float,
        end_angle: float,
        counterclockwise: bool,
    ) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def line_to(self, x: float, y: float) -> None: ...
    def arc_to(
        self, x1: float, y1: float, x2: float, y2: float, radius: float
    ) -> None: ...
    def bezier_curve_to(
        self, cp1x: float, cp1y: float, cp2x: float, cp2y: float, x: float, y: float
    ) -> None: ...
    def quadratic_curve_to(
        self, cpx: float, cpy: float, x: float, y: float
    ) -> None: ...
    def conic_curve_to(
        self, cpx: float, cpy: float, x: float, y: float, weight: float
    ) -> None: ...
    def close_path(self) -> None: ...
    def is_point_in_path(
        self, path: Path2D | None, x: float, y: float, fill_rule: str | None
    ) -> bool: ...
    def is_point_in_stroke(self, path: Path2D | None, x: float, y: float) -> bool: ...
    def clip(self, path: Path2D | None, fill_rule: str | None) -> None: ...
    def fill(self, path: Path2D | None, fill_rule: str | None) -> None: ...
    def stroke(self, path: Path2D | None) -> None: ...
    def fill_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def stroke_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def clear_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def get_fill_style(self) -> str | None: ...
    def set_fill_style(
        self, value: CanvasGradient | CanvasPattern | CanvasTexture | str
    ) -> None: ...
    def get_stroke_style(self) -> str | None: ...
    def set_stroke_style(
        self, value: CanvasGradient | CanvasPattern | CanvasTexture | str
    ) -> None: ...
    def set_line_dash_marker(self, path: Path2D | None) -> None: ...
    def get_line_dash_marker(self) -> Path2D | None: ...
    def set_line_dash_fit(self, fit_style: str) -> None: ...
    def get_line_dash_fit(self) -> str: ...
    def get_line_dash(self) -> List[float]: ...
    def set_line_dash(self, segments: Sequence[float]) -> None: ...
    def get_line_cap(self) -> str: ...
    def set_line_cap(self, cap: str) -> None: ...
    def get_line_dash_offset(self) -> float: ...
    def set_line_dash_offset(self, offset: float) -> None: ...
    def get_line_join(self) -> str: ...
    def set_line_join(self, join: str) -> None: ...
    def get_line_width(self) -> float: ...
    def set_line_width(self, num: float) -> None: ...
    def get_miter_limit(self) -> float: ...
    def set_miter_limit(self, num: float) -> None: ...
    def draw_image(
        self, source: Image | Context2D | ImageData, nums: Sequence[float]
    ) -> None: ...
    def draw_canvas(self, context: Context2D, nums: Sequence[float]) -> None: ...
    def get_image_data(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        opts: ImageDataExportOptions | None,
        canvas: Canvas,
    ) -> bytes: ...
    def put_image_data(
        self, img_data: ImageData, x: float, y: float, dirty: Sequence[float]
    ) -> None: ...
    def get_image_smoothing_enabled(self) -> bool: ...
    def set_image_smoothing_enabled(self, enabled: bool) -> None: ...
    def get_image_smoothing_quality(self) -> str: ...
    def set_image_smoothing_quality(self, name: str) -> None: ...
    def fill_text(self, text: str, x: float, y: float, width: float | None) -> None: ...
    def stroke_text(
        self, text: str, x: float, y: float, width: float | None
    ) -> None: ...
    def measure_text(self, text: str, width: float | None) -> str: ...
    def outline_text(self, text: str, width: float | None) -> Path2D: ...
    def get_font(self) -> str: ...
    def set_font(self, font: Font) -> None: ...
    def get_font_stretch(self) -> str: ...
    def set_font_stretch(self, stretch: str) -> None: ...
    def get_text_align(self) -> str: ...
    def set_text_align(self, name: str) -> None: ...
    def get_text_baseline(self) -> str: ...
    def set_text_baseline(self, name: str) -> None: ...
    def get_direction(self) -> str: ...
    def set_direction(self, name: str) -> None: ...
    def get_letter_spacing(self) -> str: ...
    def set_letter_spacing(self, spacing: Spacing) -> None: ...
    def get_word_spacing(self) -> str: ...
    def set_word_spacing(self, spacing: Spacing) -> None: ...
    def get_font_hinting(self) -> bool: ...
    def set_font_hinting(self, flag: bool) -> None: ...
    def get_font_variant(self) -> str: ...
    def set_font_variant(self, val: FontVariant) -> None: ...
    def get_text_wrap(self) -> bool: ...
    def set_text_wrap(self, flag: bool) -> None: ...
    def get_text_decoration(self) -> str: ...
    def set_text_decoration(self, style: DecorationStyle) -> None: ...
    def get_global_alpha(self) -> float: ...
    def set_global_alpha(self, alpha: float) -> None: ...
    def get_global_composite_operation(self) -> str: ...
    def set_global_composite_operation(self, name: str) -> None: ...
    def get_filter(self) -> str: ...
    def set_filter(self, arg: Filter) -> None: ...
    def get_shadow_blur(self) -> float: ...
    def set_shadow_blur(self, num: float) -> None: ...
    def get_shadow_color(self) -> str: ...
    def set_shadow_color(self, color: str) -> None: ...
    def get_shadow_offset_x(self) -> float: ...
    def get_shadow_offset_y(self) -> float: ...
    def set_shadow_offset_x(self, num: float) -> None: ...
    def set_shadow_offset_y(self, num: float) -> None: ...

# region font library

class TypefaceDetails:
    family: str
    weight: int
    slant: str
    width: str
    file: str

class FamilyDetails:
    family: str
    weights: List[float]
    widths: List[str]
    styles: List[str]

def get_families() -> List[str]: ...
def has(family_name: str) -> bool: ...
def family(family_name: str) -> FamilyDetails | None: ...
def add_family(filenames: List[str], alias: str | None) -> List[TypefaceDetails]: ...
def reset() -> None: ...

# endregion
