ARG MANYLINUX_IMAGE
ARG LLVM_VERSION=22

# --------------------------------------------------------------------------------------------------------

FROM debian:bullseye-slim AS dependencies

RUN apt-get update && apt-get install -y -q \
    git perl curl wget gpg software-properties-common pkg-config \
    build-essential ninja-build cmake python3-venv lsb-release \
    libexpat1-dev libpng-dev

# install clang
COPY install-llvm.sh .
RUN bash install-llvm.sh $LLVM_VERSION

# manually build freetype & fontconfig and install fontconfig in /usr/local
COPY ./install-fontlibs.sh /opt
COPY ./freetype.cfg /opt
RUN bash /opt/install-fontlibs.sh

# move the static libs to a common location consistent across glibc & musl builds
RUN mkdir -p /opt/skia-static-libs && \
    cp /usr/local/lib/*/libfontconfig.a /opt/skia-static-libs

# --------------------------------------------------------------------------------------------------------

FROM ${MANYLINUX_IMAGE} AS skia-build-env
ARG TARGETARCH

RUN apt-get update && apt-get install -y -q \
  curl wget perl zip software-properties-common lsb-release build-essential ninja-build fonts-dejavu-core

# install clang
COPY install-llvm.sh .
RUN bash install-llvm.sh $LLVM_VERSION

# install gh
ARG GH_VERSION=2.76.2
ARG GH_URL=https://github.com/cli/cli/releases/download/v$GH_VERSION/gh_${GH_VERSION}_linux_$TARGETARCH.tar.gz
RUN curl -sL $GH_URL | tar xz --strip-components=2 -C /usr/local/bin

# copy over results of previous build stage
COPY --from=dependencies /opt/skia-static-libs /opt/skia-static-libs

WORKDIR /opt

CMD ["bash"]
