# --------------------------------------------------------------------------------------------------------

ARG MANYLINUX_IMAGE
FROM ${MANYLINUX_IMAGE} AS extractor

# --------------------------------------------------------------------------------------------------------

FROM python:3.12-alpine3.20
ARG TARGETARCH

ENV RUSTFLAGS="-C target-feature=-crt-static" \
    LIBCLANG_PATH="/usr/lib" \
    CC="clang" \
    CXX="clang++" \
    GN_EXE="gn" \
    SKIA_GN_COMMAND="/usr/bin/gn" \
    SKIA_NINJA_COMMAND="/usr/bin/ninja"

RUN apk update && apk add --update --no-cache \
    bash curl git python3 perl build-base g++ linux-headers ttf-dejavu \
    musl-dev openssl-dev gn ninja-build

RUN apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    gperf cmake expat-static expat-dev libpng-dev \
    clang clang-dev llvm llvm-dev

# manually build freetype & fontconfig and install fontconfig in /usr/local
COPY ./install-fontlibs.sh /opt
COPY ./freetype.cfg /opt
RUN bash /opt/install-fontlibs.sh

# move the static libs to a common location consistent across glibc & musl builds
RUN mkdir -p /opt/skia-static-libs && \
    cp /usr/local/lib/libfontconfig.a /opt/skia-static-libs

# install gh
ARG GH_VERSION=2.76.2
ARG GH_URL=https://github.com/cli/cli/releases/download/v$GH_VERSION/gh_${GH_VERSION}_linux_$TARGETARCH.tar.gz
RUN curl -sL $GH_URL | tar xz --strip-components=2 -C /usr/local/bin

# copy python
COPY --from=extractor /opt /opt

WORKDIR /opt
CMD ["bash"]
