FROM messense/manylinux2014-cross:aarch64

ARG LLVM_VERSION=22

ENV CC=clang \
  CXX=clang++

RUN apt-get update && \
  apt-get install -y --fix-missing --no-install-recommends gpg-agent ca-certificates openssl && \
  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
  echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${LLVM_VERSION} main" >> /etc/apt/sources.list && \
  echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${LLVM_VERSION} main" >> /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y --fix-missing --no-install-recommends \
  curl \
  llvm-${LLVM_VERSION} \
  clang-${LLVM_VERSION} \
  lld-${LLVM_VERSION} \
  libc++-${LLVM_VERSION}-dev \
  libc++abi-${LLVM_VERSION}-dev \
  xz-utils \
  rcs \
  git \
  make \
  ninja-build && \
  ln -sf /usr/bin/clang-${LLVM_VERSION} /usr/bin/clang && \
  ln -sf /usr/bin/clang++-${LLVM_VERSION} /usr/bin/clang++ && \
  ln -sf /usr/bin/lld-${LLVM_VERSION} /usr/bin/lld && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y -q \
  git perl curl wget gpg software-properties-common pkg-config \
  build-essential ninja-build cmake python3-venv lsb-release \
  libexpat1-dev libpng-dev

# manually build freetype & fontconfig and install fontconfig in /usr/local
COPY ./install-fontlibs.sh /opt
COPY ./freetype.cfg /opt
RUN bash /opt/install-fontlibs.sh

# move the static libs to a common location consistent across glibc & musl builds
RUN mkdir -p /opt/skia-static-libs && \
    cp /usr/local/lib/*/libfontconfig.a /opt/skia-static-libs
