ARG MANYLINUX_IMAGE
ARG LLVM_VERSION=21

# --------------------------------------------------------------------------------------------------------

FROM python:3.12-alpine3.20 AS dependencies
ARG TARGETARCH

RUN apk update && apk add --update --no-cache \
    bash curl git python3 perl build-base g++ linux-headers ttf-dejavu \
    musl-dev openssl-dev gn ninja-build

RUN apk add --update --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    gperf cmake expat-static expat-dev libpng-dev \
    clang clang-dev llvm llvm-dev

# manually build freetype & fontconfig and install fontconfig in /usr/local
COPY ./install-fontlibs.sh /opt
COPY ./freetype.cfg /opt
RUN bash /opt/install-fontlibs.sh

# move the static libs to a common location consistent across glibc & musl builds
RUN mkdir -p /opt/skia-static-libs && \
    cp /usr/local/lib/libfontconfig.a /opt/skia-static-libs

# --------------------------------------------------------------------------------------------------------

FROM ${MANYLINUX_IMAGE}
ARG TARGETARCH

RUN echo "deb http://archive.ubuntu.com/ubuntu/ jammy main universe" >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y -q \
  curl wget perl zip software-properties-common lsb-release build-essential ninja-build fonts-dejavu-core

# install clang
COPY install-llvm.sh .
RUN bash install-llvm.sh $LLVM_VERSION

# install gh
ARG GH_VERSION=2.76.2
ARG GH_URL=https://github.com/cli/cli/releases/download/v$GH_VERSION/gh_${GH_VERSION}_linux_$TARGETARCH.tar.gz
RUN curl -sL $GH_URL | tar xz --strip-components=2 -C /usr/local/bin

# copy over results of previous build stage
COPY --from=dependencies /opt/skia-static-libs /opt/skia-static-libs

WORKDIR /opt
CMD ["bash"]
